### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by ulrick65** [shokinn/emby-updater#5]
Trying to update from 4.7.8.0 to the newest release, it quits out and says:

NO UPDATE AVAILABLE!
Installed version:    4.7.8.0
Available version:    4.7.11.0

I noticed there was a new release (espresso macchiato doppio) but it looks like the only change was to fix the self-updater.  However, it won't run at all...gives the following error.  The current version I have (which is the one previous) has worked right up until this current Emby update...so not sure what changed.

[26369] Error loading Python lib '/tmp/_MEIibNeNc/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIibNeNc/libpython3.8.so.1.0)

Have used your program for a long while now updating Emby...has worked great and is easy to use.  I appreciate the work on it.

Thanks.

**Comment by shokinn** [comment]
Hi ulrick,
I am in the process of moving to my new apartment, so I currently don't have time to look into it.
I guess I'll be able to check it by end of this month. I'll keep you posted when a fix is availabe.

Btw. which version do you use?
The binary ditribution or the python package via [PyPI](https://pypi.org/)?

Best

**Comment by ulrick65** [comment]
Thanks.  I appreciate it.  I use the binary one...so I couldn't really look
at it and see what might be happening.

My programming skills arent great, but I get by with some stuff.  I will
maybe have a look on Github at the source and see what I see...you never
know, sometimes a blind squirrel finds a nut as they say!

Good luck with the move, hope all goes well.

Thanks.

**Comment by shokinn** [comment]
Hi @ulrick65,
i've checked the script.
So basically the script is still fine, but the binary distribution uses an old version of glibc.
Thefore it does not start.

I would recommend that you try to use the installtion via [pipx](https://github.com/shokinn/emby-updater#with-pipx-recommended)

Basically do this:
1. Become root (`sudo -i`), since the emby updater script has to be run as root, pipx also has to be installed as root.
2. Install pip, if you don't already have (`apt install python3-pip`)
3. Install pipx (<https://github.com/shokinn/emby-updater#with-pipx-recommended>)
4. Add pipx completions to your shell (e.g. for Bash `echo 'eval "$(register-python-argcomplete pipx)"' >> ${HOME}/.bashrc`)
5. Drop root rights (`exit`)
6. Install emby-updater via pipx as documented here: (https://github.com/shokinn/emby-updater#with-pipx-recommended)

To use the emby-updater in the future you have to become root first (`sudo -i`). `sudo emby-updater` will not work since the paths from pipx are not added to your `$PATH` for your default user.

~~I think that~~ I'll discontinue the binary distribution since, I don't use emby for myself anymore and it will become to complicated to maintain that portion  
I won't discontinue the emby-updater itself, just the binary file, so installations via pipx an pip are still "supported".

Best,
Philip

**Comment by shokinn** [comment]
Oh shoot, ok the:
`NO UPDATE AVAILABLE!`
issue still exists :(

**Comment by shokinn** [comment]
Hi @ulrick65,
it's fixed.

There is also one last binary distribution.
You should be able to update your installation with
```bash
emby-updater --update
```

Best,
Philip

P.S. Please let me know if it works for you.

**Comment by ulrick65** [comment]
@shokinn 

Thanks for working on this, I appreciate it.

I tried the new binary release and I get the same error:

[30677] Error loading Python lib '/tmp/_MEIvgBKCS/libpython3.10.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIvgBKCS/libpython3.10.so.1.0)

I will go with the pipx install and see how that goes, will try that later on today.

Thanks.

**Comment by ulrick65** [comment]
@shokinn 

Installed using pipx and it works like a charm!  Thanks for the update, I appreciate it.

Have a great weekend.
